version: '3'
services:
  vulnerable_mysql:
    image: mysql:8.0
    container_name: vulnerable_mysql
    ports:
      - "3307:3306"  # Change the host port to 3307
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - mysql_data:/var/lib/mysql

  vulnerable_container:
    build: .
    container_name: vulnerable_container
    ports:
      - "8080:80"   # Modify this port mapping as needed
    depends_on:
      - vulnerable_mysql

volumes:
  mysql_data:

