version: '3'

services:
  mysql:
    image: mysql:5.7
    container_name: vulnerable_mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  vulnerable-container:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vulnerable_container
    depends_on:
      - mysql
    ports:
      - "8080:8080"

volumes:
  mysql_data:
    driver: local






